import requests
import wget
'''
flickit - search with search_text to return a list of id's
'''
# secret: bba1e7045634ee73

def flickit(search_text):
    url = "https://www.flickr.com/services/rest/"
    # API key generated by Leo - use sensibly or generate your own one :)
    api = "169ef5151303ba295de7e38c1542d81c"
    response = requests.get(url,
            params={'method': 'flickr.photos.search',
                    'api_key': api,
                    'text': search_text,
                    'per_page': 1,
                    'format': 'json',
                    'nojsoncallback': 1}).json()
    # print(response['photos']['photo'][0]['id'])
    photos_dict = response['photos']['photo']
    id_list = []
    for i in range(len(photos_dict)):
        id_list.append(photos_dict[i]['id'])
    print(id_list)
    return id_list


flickit("eiffel tower")
